const Ziggy = {
    "url":"http://localhost",
    "port":null,
    "defaults":{},
    "routes":{
        "login":{
            "uri":"login",
            "methods":["GET","HEAD"]
        },
        "logout":{
            "uri":"logout",
            "methods":["POST"]
        },
        "password.request":{
            "uri":"forgot-password",
            "methods":["GET","HEAD"]
        },
        "password.reset":{
            "uri":"reset-password{token}",
            "methods":["GET","HEAD"],
            "parameters":["token"]
        },
        "password.email":{
            "uri":"forgot-password",
            "methods":["POST"]
        },
        "password.update":{
            "uri":"reset-password",
            "methods":["POST"]
        },
        "register":{
            "uri":"register",
            "methods":["GET","HEAD"]
        },
        "verification.notice":{
            "uri":"emailverify",
            "methods":["GET","HEAD"]
        },
        "verification.verify":{
            "uri":"email/verify/{id}/{hash}",
            "methods":["GET","HEAD"],
            "parameters":["id","hash"]
        },
        "verification.send":{
            "uri":"email/verification-notification",
            "methods":["POST"]
        },
        "user-profile-information.update":{
            "uri":"user/profile-information",
            "methods":["PUT"]
        },
        "user-password.update":{
            "uri":"user/password",
            "methods":["PUT"]
        },
        "password.confirmation":{
            "uri":"user/confirmed-password-status",
            "methods":["GET","HEAD"]
        },
        "password.confirm":{
            "uri":"user/confirm-password",
            "methods":["POST"]
        },
        "two-factor.login":{
            "uri":"two-factor-challenge",
            "methods":["GET","HEAD"]
        },
        "two-factor.enable":{
            "uri":"user/two-factor-authentication",
            "methods":["POST"]
        },
        "two-factor.confirm":{
            "uri":"user/confirmed-two-factor-authentication",
            "methods":["POST"]
        },
        "two-factor.disable":{
            "uri":"user/two-factor-authentication",
            "methods":["DELETE"]
        },
        "two-factor.qr-code":{
            "uri":"user/two-factor-qr-code",
            "methods":["GET","HEAD"]
        },
        "two-factor.secret-key":{
            "uri":"user/two-factor-secret-key",
            "methods":["GET","HEAD"]
        },
        "two-factor.recovery-codes":{
            "uri":"user/two-factor-recovery-codes",
            "methods":["GET","HEAD"]
        },
        "profile.show":{
            "uri":"api/user/profile",
            "methods":["GET","HEAD"]
        },
        "other-browser-sessions.destroy":{
            "uri":"api/user/other-browser-sessions",
            "methods":["DELETE"]
        },
        "current-user-photo.destroy":{
            "uri":"api/user/profile-photo",
            "methods":["DELETE"]
        },
        "current-user.destroy":{
            "uri":"api/user",
            "methods":["DELETE"]
        },
        "sanctum.csrf-cookie":{
            "uri":"sanctum/csrf-cookie",
            "methods":["GET","HEAD"]
        },
        "telescope":{
            "uri":"telescope/{view?}",
            "methods":["GET","HEAD"],
            "wheres":{"view":"(.*)"},
            "parameters":["view"]
        },
        "laratrust.permissions.index":{
            "uri":"laratrust/permissions",
            "methods":["GET","HEAD"]
        },
        "laratrust.permissions.create":{
            "uri":"laratrust/permissions/create",
            "methods":["GET","HEAD"]
        },
        "laratrust.permissions.store":{
            "uri":"laratrust/permissions",
            "methods":["POST"]
        },
        "laratrust.permissions.edit":{
            "uri":"laratrust/permissions/{permission}/edit",
            "methods":["GET","HEAD"],"parameters":["permission"]
        },
        "laratrust.permissions.update":{
            "uri":"laratrust/permissions/{permission}",
            "methods":["PUT","PATCH"],
            "parameters":["permission"]
        },
        "laratrust.roles.index":{
            "uri":"api/roles",
            "methods":["GET","HEAD"]
        },
        "laratrust.roles.create":{
            "uri":"api/roles/create",
            "methods":["GET","HEAD"]
        },
        "laratrust.roles.store":{
            "uri":"api/roles",
            "methods":["POST"]
        },
        "laratrust.roles.show":{
            "uri":"api/roles/{role}",
            "methods":["GET","HEAD"],
            "parameters":["role"]
        },
        "laratrust.roles.edit":{
            "uri":"api/roles/{role}/edit",
            "methods":["GET","HEAD"],
            "parameters":["role"]
        },
            
        "laratrust.roles.update":{
            "uri":"api/roles/{role}",
            "methods":["PUT","PATCH"],
            "parameters":["role"]
        },
        "laratrust.roles.destroy":{
            "uri":"api/roles/{role}",
            "methods":["DELETE"],
            "parameters":["role"]
        },
        "laratrust.roles-assignment.index":{
            "uri":"laratrust/roles-assignment",
            "methods":["GET","HEAD"]
        },
        "laratrust.roles-assignment.edit":{
            "uri":"laratrust/roles-assignment/{roles_assignment}/edit",
            "methods":["GET","HEAD"],
            "parameters":["roles_assignment"]
        },
        "laratrust.roles-assignment.update":{
            "uri":"laratrust/roles-assignment/{roles_assignment}",
            "methods":["PUT","PATCH"],
            "parameters":["roles_assignment"]
        },
        "ignition.healthCheck":{
            "uri":"_ignition/health-check",
            "methods":["GET","HEAD"]
        },
        "ignition.executeSolution":{
            "uri":"_ignition/execute-solution",
            "methods":["POST"]
        },
        "ignition.updateConfig":{
            "uri":"_ignition/update-config",
            "methods":["POST"]
        },
        "permissions.list":{
            "uri":"api/permisions",
            "methods":["GET","HEAD"]
        },
        "pemissions.add":{
            "uri":"api/permisions/create",
            "methods":["GET","HEAD"]
        },
        "permissions.store":{
            "uri":"api/permisions",
            "methods":["POST"]
        },
        "permissions.edit":{
            "uri":"api/permisions/{permision}/edit",
            "methods":["GET","HEAD"],"parameters":["permision"]
        },
        "permissions.update":{
            "uri":"api/permisions/{permision}",
            "methods":["PUT","PATCH"],
            "parameters":["permision"]
        },
        "role-as.list":{
            "uri":"api/roles-assignment",
            "methods":["GET","HEAD"]
        },
        "role-as.edit":{
            "uri":"api/roles-assignment/{roles_assignment}/edit",
            "methods":["GET","HEAD"],
            "parameters":["roles_assignment"]
        },
        "role-as.update":{
            "uri":"api/roles-assignment/{roles_assignment}",
            "methods":["PUT","PATCH"],
            "parameters":["roles_assignment"]
        },
        "user.index":{
            "uri":"api/user/index",
            "methods":["GET","HEAD"]
        },
        "user.show":{
            "uri":"api/user/{$id}",
            "methods":["GET","HEAD"],
            "parameters":["$id"]
        },
        "user.delete":{
            "uri":"api/user/{$id}/delete",
            "methods":["DELETE"],
            "parameters":["$id"]
        },
        "home":{
            "uri":"/",
            "methods":["GET","HEAD"]
        },
        "dashboard":{
            "uri":"dashboard",
            "methods":["GET","HEAD"]
        },
        "posts.show":{
            "uri":"posts/{$post_id}",
            "methods":["GET","HEAD"],
            "parameters":["$post_id"]
        },
        "video.index":{
            "uri":"video/index",
            "methods":["GET","HEAD"]
        },
        "pengurus_yayasan.index":{
            "uri":"pengurus_yayasan/index",
            "methods":["GET","HEAD"]
        },
        "fles.index":{
            "uri":"file/index",
            "methods":["GET","HEAD"]
        },
        "video.show":{
            "uri":"video/{$no_video}",
            "methods":["GET","HEAD"],
            "parameters":["$no_video"]
        },
        "file.show":{
            "uri":"file/{$file_id}",
            "methods":["GET","HEAD"],
            "parameters":["$file_id"]
        },
        "file.download":{
            "uri":"file/{$file_id}/download",
            "methods":["GET","HEAD"],
            "parameters":["$file_id"]
        },
        "datayayasan.show":{
            "uri":"data_yayasan/{$yayasan_id}/show",
            "methods":["GET","HEAD"],
            "parameters":["$yayasan_id"]
        },
        "video.create":{
            "uri":"video/create",
            "methods":["GET","HEAD"]
        },
        "video.store":{
            "uri":"video/store",
            "methods":["POST"]
        },
        "video.edit":{
            "uri":"video/edit",
            "methods":["GET","HEAD"]
        },
        "video.choose":{
            "uri":"video/{$no_video}/choose",
            "methods":["GET","HEAD"],
            "parameters":["$no_video"]
        },
        "video.update":{
            "uri":"video/{$no_video}/update",
            "methods":["PUT"],
            "parameters":["$no_video"]
        },
        "video.delete":{
            "uri":"video/{$no_video}/delete",
            "methods":["DELETE"],
            "parameters":["$no_video"]
        },
        "file.create":{
            "uri":"file/create",
            "methods":["POST"]
        },
        "file.store":{
            "uri":"file/store",
            "methods":["POST"]
        },
        "file.edit":{
            "uri":"file/edit",
            "methods":["GET","HEAD"]
        },
        "file.choose":{
            "uri":"file/{$file_id}/choose",
            "methods":["GET","HEAD"],
            "parameters":["$file_id"]
        },
        "file.update":{
            "uri":"file/{$file_id}/update",
            "methods":["PUT"],
            "parameters":["$file_id"]
        },
        "file.delete":{
            "uri":"file/{$file_id}/delete",
            "methods":["DELETE"],
            "parameters":["$file_id"]
        },
        "pengurus_yayasan.create":{
            "uri":"pengurus_yayasan/create",
            "methods":["POST"]
        },
        "pengurus_yayasan.store":{
            "uri":"pengurus_yayasan/store",
            "methods":["POST"]
        },
        "pengurus_yayasan.edit":{
            "uri":"pengurus_yayasan/edit",
            "methods":["GET","HEAD"]
        },
        "pengurus_yayasan.choose":{
            "uri":"pengurus_yayasan/{$id_pengurus}/choose",
            "methods":["GET","HEAD"],
            "parameters":["$id_pengurus"]
        },
        "pengurus_yayasan.update":{
            "uri":"pengurus_yayasan/{$id_pengurus}/update",
            "methods":["PUT"],
            "parameters":["$id_pengurus"]
        },
        "pengurus_yayasan.delete":{
            "uri":"pengurus_yayasan/{$id_pengurus}/delete",
            "methods":["DELETE"],
            "parameters":["$id_pengurus"]
        },
        "post.create":{
            "uri":"post/create",
            "methods":["GET","HEAD"]
        },
        "post.store":{
            "uri":"post/store",
            "methods":["POST"]
        },
        "post.edit":{
            "uri":"post/edit",
            "methods":["GET","HEAD"]
        },
        "post.choose":{
            "uri":"post/{$post_id}/choose",
            "methods":["GET","HEAD"],
            "parameters":["$post_id"]
        },
        "post.update":{
            "uri":"post/{$post_id}/update",
            "methods":["PUT"],
            "parameters":["$post_id"]
        },
        "data_yayasan.create":{
            "uri":"data_yayasan/create",
            "methods":["GET","HEAD"]
        },
        "data_yayasan.store":{
            "uri":"data_yayasan/store",
            "methods":["POST"]
        },
        "data_yayasan.edit":{
            "uri":"data_yayasan/edit",
            "methods":["GET","HEAD"]
        },
        "data_yayasan.choose":{
            "uri":"data_yayasan/{$yayasan_id}/choose",
            "methods":["GET","HEAD"],
            "parameters":["$yayasan_id"]
        },
        "data_yayasan.update":{
            "uri":"data_yayasan/{$yayasan_id}/update",
            "methods":["PUT"],
            "parameters":["$yayasan_id"]
}
}
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
};

export {Ziggy};
