/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "laratrust.permissions.index": [],
    "laratrust.permissions.create": [],
    "laratrust.permissions.store": [],
    "laratrust.permissions.edit": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.permissions.update": [
        {
            "name": "permission",
            "required": true
        }
    ],
    "laratrust.roles.index": [],
    "laratrust.roles.create": [],
    "laratrust.roles.store": [],
    "laratrust.roles.show": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.edit": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.update": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles.destroy": [
        {
            "name": "role",
            "required": true
        }
    ],
    "laratrust.roles-assignment.index": [],
    "laratrust.roles-assignment.edit": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "laratrust.roles-assignment.update": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "permissions.list": [],
    "pemissions.add": [],
    "permissions.store": [],
    "permissions.edit": [
        {
            "name": "permision",
            "required": true
        }
    ],
    "permissions.update": [
        {
            "name": "permision",
            "required": true
        }
    ],
    "role-as.list": [],
    "role-as.edit": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "role-as.update": [
        {
            "name": "roles_assignment",
            "required": true
        }
    ],
    "user.index": [],
    "user.show": [
        {
            "name": "$id",
            "required": true
        }
    ],
    "user.delete": [
        {
            "name": "$id",
            "required": true
        }
    ],
    "home": [],
    "dashboard": [],
    "posts.show": [
        {
            "name": "$post_id",
            "required": true
        }
    ],
    "video.index": [],
    "pengurus_yayasan.index": [],
    "fles.index": [],
    "video.show": [
        {
            "name": "$no_video",
            "required": true
        }
    ],
    "file.show": [
        {
            "name": "$file_id",
            "required": true
        }
    ],
    "file.download": [
        {
            "name": "$file_id",
            "required": true
        }
    ],
    "datayayasan.show": [
        {
            "name": "$yayasan_id",
            "required": true
        }
    ],
    "video.create": [],
    "video.store": [],
    "video.edit": [],
    "video.choose": [
        {
            "name": "$no_video",
            "required": true
        }
    ],
    "video.update": [
        {
            "name": "$no_video",
            "required": true
        }
    ],
    "video.delete": [
        {
            "name": "$no_video",
            "required": true
        }
    ],
    "file.create": [],
    "file.store": [],
    "file.edit": [],
    "file.choose": [
        {
            "name": "$file_id",
            "required": true
        }
    ],
    "file.update": [
        {
            "name": "$file_id",
            "required": true
        }
    ],
    "file.delete": [
        {
            "name": "$file_id",
            "required": true
        }
    ],
    "pengurus_yayasan.create": [],
    "pengurus_yayasan.store": [],
    "pengurus_yayasan.edit": [],
    "pengurus_yayasan.choose": [
        {
            "name": "$id_pengurus",
            "required": true
        }
    ],
    "pengurus_yayasan.update": [
        {
            "name": "$id_pengurus",
            "required": true
        }
    ],
    "pengurus_yayasan.delete": [
        {
            "name": "$id_pengurus",
            "required": true
        }
    ],
    "post.create": [],
    "post.store": [],
    "post.edit": [],
    "post.choose": [
        {
            "name": "$post_id",
            "required": true
        }
    ],
    "post.update": [
        {
            "name": "$post_id",
            "required": true
        }
    ],
    "foto.edit": [],
    "foto.upload": [
        {
            "name": "$post_id",
            "required": true
        }
    ],
    "foto.choose": [
        {
            "name": "$foto_id",
            "required": true
        }
    ],
    "foto.update": [
        {
            "name": "$foto_id",
            "required": true
        }
    ],
    "foto.delete": [
        {
            "name": "$foto_id",
            "required": true
        }
    ],
    "data_yayasan.create": [],
    "data_yayasan.store": [],
    "data_yayasan.edit": [],
    "data_yayasan.choose": [
        {
            "name": "$yayasan_id",
            "required": true
        }
    ],
    "data_yayasan.update": [
        {
            "name": "$yayasan_id",
            "required": true
        }
    ]
}
}
export {};
